const mongoose = require('mongoose');

/**
 * Metadata record for every PDF generated by the system (itineraries,
 * vouchers, confirmations, invoices, receipts, quotations), so the admin
 * and customer dashboards can list/download past documents.
 */
const documentSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ['itinerary', 'hotel_voucher', 'booking_confirmation', 'invoice', 'payment_receipt', 'quotation'],
      required: true,
    },
    referenceNumber: { type: String, required: true },
    booking: { type: mongoose.Schema.Types.ObjectId, ref: 'Booking' },
    customer: { type: mongoose.Schema.Types.ObjectId, ref: 'Customer' },
    hotel: { type: mongoose.Schema.Types.ObjectId, ref: 'Hotel' }, // for hotel vouchers
    fileUrl: { type: String, required: true },
    fileName: { type: String, required: true },
    generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

documentSchema.index({ booking: 1, type: 1 });
documentSchema.index({ customer: 1 });

module.exports = mongoose.model('Document', documentSchema);
