module.exports = {
  User: require('./User'),
  Customer: require('./Customer'),
  Admin: require('./Admin'),
  Destination: require('./Destination'),
  Activity: require('./Activity'),
  Hotel: require('./Hotel'),
  TourGuide: require('./TourGuide'),
  Vehicle: require('./Vehicle'),
  Transfer: require('./Transfer'),
  TourPackage: require('./TourPackage'),
  CustomTourRequest: require('./CustomTourRequest'),
  Itinerary: require('./Itinerary'),
  Message: require('./Message'),
  Booking: require('./Booking'),
  Payment: require('./Payment'),
  Review: require('./Review'),
  Blog: require('./Blog'),
  Notification: require('./Notification'),
  Document: require('./Document'),
  HotelVoucher: require('./HotelVoucher'),
  Report: require('./Report'),
  Settings: require('./Settings'),
  Contact: require('./Contact'),
  BirthdayConfig: require('./BirthdayConfig'),
  BirthdayLog: require('./BirthdayLog'),
};
